#!/usr/bin/env python3

from math import sqrt

print("SquareRooter App")
name = input("What is your name? ")
number = input("{}, enter a number to root: ".format(name))
number = int(number)
root = sqrt(number)
print("Your root is: {}".format(str(root)))